package com.yaz.kyotaidoshin.util;


//import io.quarkus.runtime.annotations.RegisterForReflection;
//
//@RegisterForReflection(
//    serialization = true,
//    ignoreNested = false,
//    registerFullHierarchy = true,
//    targets = {
//        com.yaz.kyotaidoshin.core.service.mailer.MailerConfig.class,
//        com.fasterxml.jackson.databind.json.JsonMapper.class,
//        com.yaz.kyotaidoshin.core.service.csv.CsvReceipt.class,
//        com.yaz.kyotaidoshin.core.service.csv.Row.class,
//        com.yaz.kyotaidoshin.persistence.model.Apartment.class,
//        com.yaz.kyotaidoshin.persistence.model.Building.class,
//        com.yaz.kyotaidoshin.persistence.model.Debt.class,
//        com.yaz.kyotaidoshin.persistence.model.Expense.class,
//        com.yaz.kyotaidoshin.persistence.model.ExtraCharge.class,
//        com.yaz.kyotaidoshin.persistence.model.NotificationEvent.class,
//        com.yaz.kyotaidoshin.persistence.model.OidcDbToken.class,
//        com.yaz.kyotaidoshin.persistence.model.Rate.class,
//        com.yaz.kyotaidoshin.persistence.model.Receipt.class,
//        com.yaz.kyotaidoshin.persistence.model.ReserveFund.class,
//        com.yaz.kyotaidoshin.persistence.model.User.class,
//        com.yaz.kyotaidoshin.persistence.model.domain.ExpenseType.class,
//        com.yaz.kyotaidoshin.persistence.model.domain.IdentityProvider.class,
//        com.yaz.kyotaidoshin.persistence.model.domain.ReserveFundType.class,
//        com.yaz.kyotaidoshin.core.service.ReceiptFileService.SendReceiptRequest.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.Listener.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.TursoResult.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.Batch.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.BatchCond.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.BatchReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.BatchStep.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.CloseCursorReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.CloseSqlReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.CloseStreamReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.DescribeReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.ExecuteReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.FetchCursorReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.GetAutocommitReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.HelloMsg.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.NamedArg.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.OpenCursorReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.OpenStreamReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.Request.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.RequestMsg.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.SequenceReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.Stmt.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.StoreSqlReq.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.request.Value.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.response.Col.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.response.Error.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.response.ExecuteResp.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.response.HelloRes.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.response.Response.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.response.ResponseMsg.class,
//        com.yaz.kyotaidoshin.persistence.turso.ws.response.StmtResult.class,
//        io.quarkiverse.renarde.security.RenardeUser.class,
//        java.io.Serializable.class,
//        java.lang.Comparable.class,
//        java.lang.Enum.class,
//        java.lang.Object.class,
//        java.lang.Record.class,
//        java.lang.constant.Constable.class,
//        org.apache.commons.logging.impl.WeakHashtable.class,
//        org.apache.xmlbeans.metadata.system.sXMLCONFIG.TypeSystemHolder.class,
//        org.apache.xmlbeans.metadata.system.sXMLLANG.TypeSystemHolder.class,
//        org.apache.xmlbeans.metadata.system.sXMLSCHEMA.TypeSystemHolder.class,
//        org.apache.xmlbeans.metadata.system.sXMLTOOLS.TypeSystemHolder.class,
//        org.openxmlformats.schemas.drawingml.x2006.main.impl.ThemeDocumentImpl.class,
//        org.openxmlformats.schemas.officeDocument.x2006.sharedTypes.impl.STXstringImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTBorderImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTBordersImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTCellStyleXfsImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTCellXfsImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTDxfsImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTFillImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTFillsImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTFontImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTFontsImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTNumFmtImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTNumFmtsImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTStylesheetImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTTableStylesImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTXfImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.STCellStyleXfIdImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.STNumFmtIdImpl.class,
//        org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.StyleSheetDocumentImpl.class
//    })
public class NativeRegistration {

}
